import type { Campaign } from "./schema";

export const CAMPAIGNS: Campaign[] = [
	{
		slug: "clinicas-talatona",
		name: "Clínicas Talatona",
		sector: "Clínicas privadas",
		service: "Sistema de marcações",
		locations: ["Talatona", "Kilamba"],
		state: "ENRICHING",
		qualifiedCount: 38,
		spendUsd: 1.12,
		limitUsd: 1.5,
		funnel: {
			scraped: 142,
			scrapeCostUsd: 0.84,
			kept: 96,
			filterNote: "46 fora: sem telefone, poucas reviews, clientes",
			cutShare: 0.4,
			qualified: 38,
			enriched: 14,
			enrichCostUsd: 0.28,
			enriching: true,
		},
		nextRun: { query: "Clínicas em Belas e Kilamba", places: 160, costUsd: 0.64 },
		enrichCostUsd: 0.31,
	},
	{
		slug: "restaurantes-maianga",
		name: "Restaurantes Maianga",
		sector: "Restaurantes",
		service: "Website com reservas",
		locations: ["Maianga", "Ingombota", "Miramar"],
		state: "DONE",
		qualifiedCount: 24,
		spendUsd: 0.97,
		limitUsd: 2,
		funnel: {
			scraped: 118,
			scrapeCostUsd: 0.56,
			kept: 61,
			filterNote: "57 fora: cadeias, sem telefone, poucas reviews",
			cutShare: 0.4,
			qualified: 24,
			enriched: 24,
			enrichCostUsd: 0.41,
			enriching: false,
		},
		nextRun: { query: "Restaurantes em Maianga, Ingombota e Miramar", places: 120, costUsd: 0.48 },
		enrichCostUsd: 0,
	},
	{
		slug: "escolas-viana",
		name: "Escolas Viana",
		sector: "Escolas privadas",
		service: "Portal para pais",
		locations: ["Viana", "Cazenga", "Zango"],
		state: "DONE",
		qualifiedCount: 17,
		spendUsd: 0.78,
		limitUsd: 1,
		funnel: {
			scraped: 118,
			scrapeCostUsd: 0.78,
			kept: 43,
			filterNote: "75 fora: unidades públicas, poucas reviews",
			cutShare: 0.4,
			qualified: 17,
			enriched: 17,
			enrichCostUsd: 0,
			enriching: false,
		},
		nextRun: { query: "Escolas privadas em Viana, Cazenga e Zango", places: 110, costUsd: 0.44 },
		enrichCostUsd: 0,
	},
	{
		slug: "oficinas-zango",
		name: "Oficinas Zango",
		sector: "Oficinas auto",
		service: "Website com WhatsApp",
		locations: ["Zango", "Viana"],
		state: "FAILED",
		qualifiedCount: 6,
		spendUsd: 0.55,
		limitUsd: 1,
		funnel: {
			scraped: 64,
			scrapeCostUsd: 0.55,
			kept: 15,
			filterNote: "49 fora: sem telefone, poucas reviews",
			cutShare: 0.4,
			qualified: 6,
			enriched: 0,
			enrichCostUsd: 0,
			enriching: false,
		},
		nextRun: { query: "Oficinas auto no Zango e em Viana", places: 210, costUsd: 0.84 },
		enrichCostUsd: 0.02,
	},
	{
		slug: "laboratorios-luanda",
		name: "Laboratórios Luanda",
		sector: "Laboratórios",
		service: "Sistema de marcações",
		locations: ["Maianga", "Alvalade"],
		state: "DRAFT",
		qualifiedCount: 0,
		spendUsd: 0,
		limitUsd: 1,
		funnel: null,
		nextRun: { query: "Laboratórios em Maianga e Alvalade", places: 90, costUsd: 0.36 },
		enrichCostUsd: 0,
	},
];
