/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AppEmpresaRouteImport } from './routes/_app.empresa'
import { Route as AppEstadosRouteImport } from './routes/_app.estados'
import { Route as AppHojeRouteImport } from './routes/_app.hoje'
import { Route as AppUsoRouteImport } from './routes/_app.uso'
import { Route as AppCampanhasIndexRouteImport } from './routes/_app.campanhas.index'
import { Route as AppCampanhasSlugRouteImport } from './routes/_app.campanhas.$slug'
import { Route as AppCampanhasNovaRouteImport } from './routes/_app.campanhas.nova'
import { Route as AppLeadsIndexRouteImport } from './routes/_app.leads.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app.leads.$leadId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadosRoute = AppEstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => AppRoute,
} as any)
const AppHojeRoute = AppHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AppRoute,
} as any)
const AppUsoRoute = AppUsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasIndexRoute = AppCampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasSlugRoute = AppCampanhasSlugRouteImport.update({
  id: '/campanhas/$slug',
  path: '/campanhas/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasNovaRoute = AppCampanhasNovaRouteImport.update({
  id: '/campanhas/nova',
  path: '/campanhas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/empresa': typeof AppEmpresaRoute
  '/estados': typeof AppEstadosRoute
  '/hoje': typeof AppHojeRoute
  '/uso': typeof AppUsoRoute
  '/campanhas/$slug': typeof AppCampanhasSlugRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campanhas/': typeof AppCampanhasIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/empresa': typeof AppEmpresaRoute
  '/estados': typeof AppEstadosRoute
  '/hoje': typeof AppHojeRoute
  '/uso': typeof AppUsoRoute
  '/campanhas/$slug': typeof AppCampanhasSlugRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campanhas': typeof AppCampanhasIndexRoute
  '/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/estados': typeof AppEstadosRoute
  '/_app/hoje': typeof AppHojeRoute
  '/_app/uso': typeof AppUsoRoute
  '/_app/campanhas/$slug': typeof AppCampanhasSlugRoute
  '/_app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/campanhas/': typeof AppCampanhasIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/empresa'
    | '/estados'
    | '/hoje'
    | '/uso'
    | '/campanhas/$slug'
    | '/campanhas/nova'
    | '/leads/$leadId'
    | '/api/auth/$'
    | '/campanhas/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/empresa'
    | '/estados'
    | '/hoje'
    | '/uso'
    | '/campanhas/$slug'
    | '/campanhas/nova'
    | '/leads/$leadId'
    | '/api/auth/$'
    | '/campanhas'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/entrar'
    | '/_app/empresa'
    | '/_app/estados'
    | '/_app/hoje'
    | '/_app/uso'
    | '/_app/campanhas/$slug'
    | '/_app/campanhas/nova'
    | '/_app/leads/$leadId'
    | '/api/auth/$'
    | '/_app/campanhas/'
    | '/_app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estados': {
      id: '/_app/estados'
      path: '/estados'
      fullPath: '/estados'
      preLoaderRoute: typeof AppEstadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hoje': {
      id: '/_app/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AppHojeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uso': {
      id: '/_app/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof AppUsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/': {
      id: '/_app/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof AppCampanhasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/$slug': {
      id: '/_app/campanhas/$slug'
      path: '/campanhas/$slug'
      fullPath: '/campanhas/$slug'
      preLoaderRoute: typeof AppCampanhasSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/nova': {
      id: '/_app/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof AppCampanhasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppEstadosRoute: typeof AppEstadosRoute
  AppHojeRoute: typeof AppHojeRoute
  AppUsoRoute: typeof AppUsoRoute
  AppCampanhasSlugRoute: typeof AppCampanhasSlugRoute
  AppCampanhasNovaRoute: typeof AppCampanhasNovaRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppCampanhasIndexRoute: typeof AppCampanhasIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEmpresaRoute: AppEmpresaRoute,
  AppEstadosRoute: AppEstadosRoute,
  AppHojeRoute: AppHojeRoute,
  AppUsoRoute: AppUsoRoute,
  AppCampanhasSlugRoute: AppCampanhasSlugRoute,
  AppCampanhasNovaRoute: AppCampanhasNovaRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppCampanhasIndexRoute: AppCampanhasIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EntrarRoute: EntrarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
