/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EstadosRouteImport } from './routes/estados'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as UsoRouteImport } from './routes/uso'
import { Route as CampanhasIndexRouteImport } from './routes/campanhas.index'
import { Route as CampanhasSlugRouteImport } from './routes/campanhas.$slug'
import { Route as CampanhasNovaRouteImport } from './routes/campanhas.nova'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadosRoute = EstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const UsoRoute = UsoRouteImport.update({
  id: '/uso',
  path: '/uso',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIndexRoute = CampanhasIndexRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasSlugRoute = CampanhasSlugRouteImport.update({
  id: '/campanhas/$slug',
  path: '/campanhas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasNovaRoute = CampanhasNovaRouteImport.update({
  id: '/campanhas/nova',
  path: '/campanhas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/estados': typeof EstadosRoute
  '/hoje': typeof HojeRoute
  '/uso': typeof UsoRoute
  '/campanhas/$slug': typeof CampanhasSlugRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campanhas/': typeof CampanhasIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/estados': typeof EstadosRoute
  '/hoje': typeof HojeRoute
  '/uso': typeof UsoRoute
  '/campanhas/$slug': typeof CampanhasSlugRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campanhas': typeof CampanhasIndexRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresa': typeof EmpresaRoute
  '/estados': typeof EstadosRoute
  '/hoje': typeof HojeRoute
  '/uso': typeof UsoRoute
  '/campanhas/$slug': typeof CampanhasSlugRoute
  '/campanhas/nova': typeof CampanhasNovaRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/campanhas/': typeof CampanhasIndexRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresa'
    | '/estados'
    | '/hoje'
    | '/uso'
    | '/campanhas/$slug'
    | '/campanhas/nova'
    | '/leads/$leadId'
    | '/campanhas/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresa'
    | '/estados'
    | '/hoje'
    | '/uso'
    | '/campanhas/$slug'
    | '/campanhas/nova'
    | '/leads/$leadId'
    | '/campanhas'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/empresa'
    | '/estados'
    | '/hoje'
    | '/uso'
    | '/campanhas/$slug'
    | '/campanhas/nova'
    | '/leads/$leadId'
    | '/campanhas/'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresaRoute: typeof EmpresaRoute
  EstadosRoute: typeof EstadosRoute
  HojeRoute: typeof HojeRoute
  UsoRoute: typeof UsoRoute
  CampanhasSlugRoute: typeof CampanhasSlugRoute
  CampanhasNovaRoute: typeof CampanhasNovaRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  CampanhasIndexRoute: typeof CampanhasIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estados': {
      id: '/estados'
      path: '/estados'
      fullPath: '/estados'
      preLoaderRoute: typeof EstadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uso': {
      id: '/uso'
      path: '/uso'
      fullPath: '/uso'
      preLoaderRoute: typeof UsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/': {
      id: '/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof CampanhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/$slug': {
      id: '/campanhas/$slug'
      path: '/campanhas/$slug'
      fullPath: '/campanhas/$slug'
      preLoaderRoute: typeof CampanhasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/nova': {
      id: '/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof CampanhasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresaRoute: EmpresaRoute,
  EstadosRoute: EstadosRoute,
  HojeRoute: HojeRoute,
  UsoRoute: UsoRoute,
  CampanhasSlugRoute: CampanhasSlugRoute,
  CampanhasNovaRoute: CampanhasNovaRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  CampanhasIndexRoute: CampanhasIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
